In [1]:
import pandas as pd

In [2]:
pers = pd.read_csv('Class_pers.csv')
pers.head()

  Enrol No.    Name Sex  Age Address Interest
0      A101  George   M   10    abcd    music
1      A102  Monica   F   11     cds    music
2      A103  Jennie   F   11     wes    dance
3      A104   Baley   M   12     adf   sports
4      A105  Garret   M   10      as   sports

In [3]:
marks = pd.read_csv('Class_marks.csv')
marks.head()

  Enrol No.  Maths  Science  English
0      A101     16       15       12
1      A102     16       17       11
2      A103     12       18       17
3      A104     11       13       16
4      A105     11       10       15

## Merging --> joining 2 datasets based on atleast 1 common column
```python
pd.merge(df1, df2, how = {'inner', 'left', 'right', 'outer'}, on = <primary key>)
```

In [4]:
pers.columns

Index(['Enrol No.', 'Name', 'Sex', 'Age', 'Address', 'Interest'], dtype='object')

In [5]:
marks.columns

Index(['Enrol No.', 'Maths', 'Science', 'English'], dtype='object')

In [6]:
pd.merge(pers, marks, how = 'inner', on = 'Enrol No.')

   Enrol No.     Name Sex  Age  Address Interest  Maths  Science  English
0       A101   George   M   10     abcd    music     16       15       12
1       A102   Monica   F   11      cds    music     16       17       11
2       A103   Jennie   F   11      wes    dance     12       18       17
3       A104    Baley   M   12      adf   sports     11       13       16
4       A105   Garret   M   10       as   sports     11       10       15
5       A106   Warren   M   12     afee     arts     10       18       14
6       A107    Janet   F   10      cfd   sports     14       14       11
7       A108     John   M   11       tt     arts     19       15       12
8       A109    Maria   F   10     njjn    music     19       11       13
9       A110     Sean   M   10     rdfe   sports     16       13       18
10      A111  Cynthia   F   12       df     arts     15       13       14
11      A112     Rita   F   11     eghj    music     16       17       19
12      A113    Maria   F   11      eer   sports     13       19       10
13      A114      Leo   M   12   wjjjfj     arts     12       19       17
14      A115    Keith   M   11   kfyhty   sports     18       19       17
15      A116   Nicole   F   11  jdhffjn   sports     12       20       17
16      A117     Dave   M   11  shbhdbj   sports     10       18       11
17      A118     Fred   M   10     sbdf    music     11       17       10
18      A119    Annie   F   12     cdjb     arts     15       19       12
19      A120    Frank   M   11    nsdbj     arts     19       19       20

In [7]:
pers = pd.DataFrame({'EnrolNo': ['A101', 'A102', 'A109', 'A107', 'A110', 'A112'],
                    'Names': ['Aman', 'Shreay', 'Paul', 'Sam', 'John', 'Kia'],
                    'Interest' : ['Music', 'Arts', 'Music', 'Arts', 'Drama', 'Arts'],
                    'Age' : [12,13,12, 13,13, 12]})

marks = pd.DataFrame({'EnrolNo': ['A001', 'A102', 'A105', 'A109', 'A110'],
                     'English':[33, 44, 35, 37, 49],
                     'Math': [44,41,32, 30, 43] })

### inner merge : includes only matching rows

In [8]:
inner_merge = pd.merge(pers, marks, how = 'inner', on = 'EnrolNo') 
inner_merge

  EnrolNo   Names Interest  Age  English  Math
0    A102  Shreay     Arts   13       44    41
1    A109    Paul    Music   12       37    30
2    A110    John    Drama   13       49    43


### outer merge: includes all rows

In [10]:
outer_merge = pd.merge(pers, marks, how = 'outer', on = 'EnrolNo')
outer_merge.fillna('-')

  EnrolNo   Names Interest   Age English  Math
0    A001       -        -     -    33.0  44.0
1    A101    Aman    Music  12.0       -     -
2    A102  Shreay     Arts  13.0    44.0  41.0
3    A105       -        -     -    35.0  32.0
4    A107     Sam     Arts  13.0       -     -
5    A109    Paul    Music  12.0    37.0  30.0
6    A110    John    Drama  13.0    49.0  43.0
7    A112     Kia     Arts  12.0       -     -

In [12]:
outer_merge = pd.merge(pers, marks, how = 'outer', on = 'EnrolNo', indicator = True)
outer_merge

  EnrolNo   Names Interest   Age  English  Math      _merge
0    A001     NaN      NaN   NaN     33.0  44.0  right_only
1    A101    Aman    Music  12.0      NaN   NaN   left_only
2    A102  Shreay     Arts  13.0     44.0  41.0        both
3    A105     NaN      NaN   NaN     35.0  32.0  right_only
4    A107     Sam     Arts  13.0      NaN   NaN   left_only
5    A109    Paul    Music  12.0     37.0  30.0        both
6    A110    John    Drama  13.0     49.0  43.0        both
7    A112     Kia     Arts  12.0      NaN   NaN   left_only

### left merge : rows from only 1st df ( left df )

In [14]:
left_merge = pd.merge(pers, marks, how = 'left', on = 'EnrolNo', indicator= True) 
left_merge

  EnrolNo   Names Interest  Age  English  Math     _merge
0    A101    Aman    Music   12      NaN   NaN  left_only
1    A102  Shreay     Arts   13     44.0  41.0       both
2    A109    Paul    Music   12     37.0  30.0       both
3    A107     Sam     Arts   13      NaN   NaN  left_only
4    A110    John    Drama   13     49.0  43.0       both
5    A112     Kia     Arts   12      NaN   NaN  left_only

### right merge : rows from only 2nd df ( right df )

In [15]:
right_merge = pd.merge(pers, marks, how = 'right', on = 'EnrolNo', indicator= True) 
right_merge

  EnrolNo   Names Interest   Age  English  Math      _merge
0    A001     NaN      NaN   NaN       33    44  right_only
1    A102  Shreay     Arts  13.0       44    41        both
2    A105     NaN      NaN   NaN       35    32  right_only
3    A109    Paul    Music  12.0       37    30        both
4    A110    John    Drama  13.0       49    43        both

In [16]:
pers = pd.DataFrame({'EnrolNo': ['A101', 'A102', 'A109', 'A107', 'A110', 'A112'],
                    'Names': ['Aman', 'Shreay', 'Paul', 'Sam', 'John', 'Kia'],
                    'Interest' : ['Music', 'Arts', 'Music', 'Arts', 'Drama', 'Arts'],
                    'Age' : [12,13,12, 13,13, 12]})

marks = pd.DataFrame({'EnrolNo': ['A001', 'A102', 'A105', 'A109', 'A110'],
                      'Names' : ['Amy', 'Shreya', 'Mary', 'Paul', 'John'],
                     'English':[33, 44, 35, 37, 49],
                     'Math': [44,41,32, 30, 43] })

In [17]:
merged = pd.merge(pers, marks, how = 'inner', on = 'EnrolNo', indicator= True) 
merged

  EnrolNo Names_x Interest  Age Names_y  English  Math _merge
0    A102  Shreay     Arts   13  Shreya       44    41   both
1    A109    Paul    Music   12    Paul       37    30   both
2    A110    John    Drama   13    John       49    43   both

In [18]:
merged = pd.merge(pers, marks, how = 'inner', on = 'EnrolNo', suffixes = ('_Pers', '_Marks'), indicator= True) 
merged

  EnrolNo Names_Pers Interest  Age Names_Marks  English  Math _merge
0    A102     Shreay     Arts   13      Shreya       44    41   both
1    A109       Paul    Music   12        Paul       37    30   both
2    A110       John    Drama   13        John       49    43   both

In [19]:
pers = pd.DataFrame({'EnrolNo': ['A101', 'A102', 'A109', 'A107', 'A110', 'A112'],
                    'Names': ['Aman', 'Shreay', 'Paul', 'Sam', 'John', 'Kia'],
                    'Interest' : ['Music', 'Arts', 'Music', 'Arts', 'Drama', 'Arts'],
                    'Age' : [12,13,12, 13,13, 12]})

marks = pd.DataFrame({'Id': ['A001', 'A102', 'A105', 'A109', 'A110'],
                      'Names' : ['Amy', 'Shreya', 'Mary', 'Paul', 'John'],
                     'English':[33, 44, 35, 37, 49],
                     'Math': [44,41,32, 30, 43] })

In [20]:
merged = pd.merge(pers, marks, how = 'inner', left_on = 'EnrolNo', right_on = 'Id' )
merged

  EnrolNo Names_x Interest  Age    Id Names_y  English  Math
0    A102  Shreay     Arts   13  A102  Shreya       44    41
1    A109    Paul    Music   12  A109    Paul       37    30
2    A110    John    Drama   13  A110    John       49    43

## More than 2 datasets

In [21]:
att = pd.DataFrame({'EnrolNo': ['A101', 'A109', 'A110'],
                   'att' : ['70%', '85%', '100%']})

In [22]:
pd.merge(merged, att)

  EnrolNo Names_x Interest  Age    Id Names_y  English  Math   att
0    A109    Paul    Music   12  A109    Paul       37    30   85%
1    A110    John    Drama   13  A110    John       49    43  100%

#### pd.concat combines based on index labels

In [27]:
pd.concat([pers, marks, att], axis = 1, join = 'outer')

  EnrolNo   Names Interest  Age    Id   Names  English  Math EnrolNo   att
0    A101    Aman    Music   12  A001     Amy     33.0  44.0    A101   70%
1    A102  Shreay     Arts   13  A102  Shreya     44.0  41.0    A109   85%
2    A109    Paul    Music   12  A105    Mary     35.0  32.0    A110  100%
3    A107     Sam     Arts   13  A109    Paul     37.0  30.0     NaN   NaN
4    A110    John    Drama   13  A110    John     49.0  43.0     NaN   NaN
5    A112     Kia     Arts   12   NaN     NaN      NaN   NaN     NaN   NaN

In [26]:
pd.concat([pers.set_index('EnrolNo'), marks.set_index('Id'), att.set_index('EnrolNo')], axis = 1, join = 'outer')

       Names Interest   Age   Names  English  Math   att
A101    Aman    Music  12.0     NaN      NaN   NaN   70%
A102  Shreay     Arts  13.0  Shreya     44.0  41.0   NaN
A109    Paul    Music  12.0    Paul     37.0  30.0   85%
A107     Sam     Arts  13.0     NaN      NaN   NaN   NaN
A110    John    Drama  13.0    John     49.0  43.0  100%
A112     Kia     Arts  12.0     NaN      NaN   NaN   NaN
A001     NaN      NaN   NaN     Amy     33.0  44.0   NaN
A105     NaN      NaN   NaN    Mary     35.0  32.0   NaN

## Missing Value Handling
- if a column has 30% or more missing in a column --> that column is unreliable-- remove the column
- else use imputation technique
- When preparing data for predictive modelling, do not impute in the target column using generic strategies.
- Imputation - using mean, median or mode, for time series --> forwardfill, backfill.
- You can choose granularity to come up with the value to impute

In [28]:
titanic = pd.read_csv('train.csv')

In [30]:
(titanic.isnull().sum()/titanic.shape[0]*100).round(1)

PassengerId     0.0
Survived        0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            19.9
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.0
Cabin          77.1
Embarked        0.2
dtype: float64

In [31]:
titanic.Age.mean()

np.float64(29.69911764705882)

In [32]:
titanic.Age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [33]:
titanic.groupby('Sex')[['Age']].mean()

              Age
Sex
female  27.915709
male    30.726645

In [34]:
titanic.Name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

### Identify age groups based on titles

In [50]:
titanic['titles'] = titanic.Name.str.split('[,.]').str[1].str.strip()
titanic['titles'].unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'the Countess',
       'Jonkheer'], dtype=object)

```python
young_males = ['Master']
young_females = ['Miss', 'Mlle']
adult_males = ['Mr', 'Don', 'Rev', 'Dr', 'Major', 'Sir',  'Col', 'Capt', 'Jonkheer']
adult_female = ['Mrs','Mme', 'Ms', 'Lady', 'the Countess']
```

In [53]:
def age_category(title):
    if title in  ['Master']:  return 'young males'
    elif title in ['Miss', 'Mlle']: return 'young females'
    elif title in ['Mr', 'Don', 'Rev', 'Dr', 'Major', 'Sir',  'Col', 'Capt', 'Jonkheer']: return 'adult males'
    elif title in ['Mrs','Mme', 'Ms', 'Lady', 'the Countess']: return 'adult female'
    else : return "No Category"

In [54]:
titanic['Age_category'] = titanic['titles'].apply(age_category)
titanic['Age_category']

0        adult males
1       adult female
2      young females
3       adult female
4        adult males
           ...
886      adult males
887    young females
888    young females
889      adult males
890      adult males
Name: Age_category, Length: 891, dtype: object

In [60]:
titanic.groupby('Age_category').agg({'Age': ['mean', lambda x: x.isna().sum()]})

                     Age
                    mean <lambda_0>
Age_category
adult female   35.803571         17
adult males    33.022727        120
young females  21.804054         36
young males     4.574167          4

In [62]:
titanic.Age.isna().sum()

np.int64(177)

In [67]:
titanic.Embarked.value_counts(dropna = False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [68]:
titanic.Embarked.fillna('S').value_counts(dropna = False)

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [75]:
age_grp = titanic.groupby('Age_category')['Age'].mean()
age_grp

Age_category
adult female     35.803571
adult males      33.022727
young females    21.804054
young males       4.574167
Name: Age, dtype: float64

In [76]:
age_grp.loc['adult female']

np.float64(35.80357142857143)

In [80]:
age_grp.index.tolist()

['adult female', 'adult males', 'young females', 'young males']

In [86]:
for agecat in age_grp.index.tolist():
    titanic.loc[(titanic.Age_category == agecat) & (titanic.Age.isnull()), 'Age'] = age_grp[agecat]

In [87]:
titanic.Age.isna().sum()

np.int64(0)

### Feature Engineering - Transformations

* Scaling - normalizing the ranges
* Encoding - Categorical ---> one hot encoding / label encoders
* Creation - combining multiple vars to create 1
* Binning - converting numerica to ranged categorical

### Train test split.
* Train --> 70 - 80% is used for model development
* Test --> 20 - 30% is used to validate the model
--- 
<center> <b>All transformations are done after the train test split to avoid DATA LEAKAGE

---

## Encoding
Label Encoder --> Labesl to numbers

In [89]:
cities = pd.Series(['New York', 'New York', 'Sydney', 'New Delhi', 'New Delhi', 'Sydney', 'London', 'London'])

In [90]:
cities

0     New York
1     New York
2       Sydney
3    New Delhi
4    New Delhi
5       Sydney
6       London
7       London
dtype: object

In [92]:
from sklearn.preprocessing import LabelEncoder

In [96]:
le = LabelEncoder()
le.fit(cities)
cities_le = pd.Series(le.transform(cities))

In [98]:
pd.concat([cities, cities_le], axis = 1)

           0  1
0   New York  2
1   New York  2
2     Sydney  3
3  New Delhi  1
4  New Delhi  1
5     Sydney  3
6     London  0
7     London  0

In [103]:
travel = pd.Series(['Economy', 'Economy+','Economy','Economy','Economy', 'Business','Economy','Economy+', 'First Class', 'Business', 'Economy+'])

In [104]:
travel

0         Economy
1        Economy+
2         Economy
3         Economy
4         Economy
5        Business
6         Economy
7        Economy+
8     First Class
9        Business
10       Economy+
dtype: object

In [105]:
le = LabelEncoder()
le.fit(travel)
travel_le = pd.Series(le.transform(travel))
pd.concat([travel, travel_le], axis = 1)

              0  1
0       Economy  1
1      Economy+  2
2       Economy  1
3       Economy  1
4       Economy  1
5      Business  0
6       Economy  1
7      Economy+  2
8   First Class  3
9      Business  0
10     Economy+  2

In [106]:
from sklearn.preprocessing import OrdinalEncoder

In [112]:
travel.values.reshape(-1,1)

array([['Economy'],
       ['Economy+'],
       ['Economy'],
       ['Economy'],
       ['Economy'],
       ['Business'],
       ['Economy'],
       ['Economy+'],
       ['First Class'],
       ['Business'],
       ['Economy+']], dtype=object)

In [117]:
ode = OrdinalEncoder(categories = [['Economy', 'Economy+', 'Business','First Class' ]])
ode.fit(travel.values.reshape(-1,1))
travel_ode = pd.Series(ode.transform(travel.values.reshape(-1,1)).flatten())

In [118]:
pd.concat([travel, travel_le, travel_ode], axis = 1)

              0  1    2
0       Economy  1  0.0
1      Economy+  2  1.0
2       Economy  1  0.0
3       Economy  1  0.0
4       Economy  1  0.0
5      Business  0  2.0
6       Economy  1  0.0
7      Economy+  2  1.0
8   First Class  3  3.0
9      Business  0  2.0
10     Economy+  2  1.0

### dummy creation one hot encoding

In [120]:
titanic.drop(columns = ['Name', 'PassengerId', 'Ticket', 'Cabin', 'titles'], inplace = True)

In [125]:
pd.get_dummies(titanic, drop_first= True, dtype = int )

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,Age_category_adult males,Age_category_young females,Age_category_young males
0,0,3,22.000000,1,0,7.2500,1,0,1,1,0,0
1,1,1,38.000000,1,0,71.2833,0,0,0,0,0,0
2,1,3,26.000000,0,0,7.9250,0,0,1,0,1,0
3,1,1,35.000000,1,0,53.1000,0,0,1,0,0,0
4,0,3,35.000000,0,0,8.0500,1,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,1,0,1,1,0,0
887,1,1,19.000000,0,0,30.0000,0,0,1,0,1,0
888,0,3,21.804054,1,2,23.4500,0,0,1,0,1,0
889,1,1,26.000000,0,0,30.0000,1,0,0,1,0,0
890,0,3,32.000000,0,0,7.7500,1,1,0,1,0,0

In [ ]:
Standardization -->