# Pandas

1. Series - 1 dimensional Array like labelled datastructure
2. DataFrame - 2 Dimensional Array-like labelled data structure

### Installing pandas and other required libraries

In [ ]:
%pip install pandas
%pip install scikit-learn
%pip install matplotlib
%pip install seaborn

In [5]:
# import pandas
import pandas as pd

## 1. Creating Series

### 1.1 From List

In [6]:
# Simple Series from a list
s = pd.Series([10, 20, 30, 40, 50])
print("Series from list:")
print(s)
print(f"\nType: {type(s)}")
print(f"Data type of values: {s.dtype}")

Series from list:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Type: <class 'pandas.Series'>
Data type of values: int64

### 1.2 From List with Custom Index

In [7]:
# simple list with custom index:
s = pd.Series([10, 20, 30, 40, 50], index = ['A', 'B', 'C','D', 'E'])
print("Series from list:")
print(s)

Series from list:
A    10
B    20
C    30
D    40
E    50
dtype: int64

### 1.3 From Dictionary

In [8]:
# Dictionary becomes Series with keys as index
prices = {'apple': 100, 'banana': 150, 'orange': 120, 'mango': 200}
s = pd.Series(prices)
print("Series from dictionary:")
print(s)
print(f"\nIndex comes from dictionary keys: {s.index.tolist()}")

Series from dictionary:
apple     100
banana    150
orange    120
mango     200
dtype: int64

Index comes from dictionary keys: ['apple', 'banana', 'orange', 'mango']

### 1.4. Accessing Series Elements

In [10]:
# usig label
print(f"Price for apple: Rs { s['apple']}")

# multiple elements
print(f"Price for apples & mangos: \n{ s[['apple', 'mango']]}")

Price for apple: Rs 100
Price for apples & mangos:
apple    100
mango    200
dtype: int64

In [11]:
# usig label -> .loc
print(f"Price for apple: Rs { s.loc['apple']}")

Price for apple: Rs 100

In [12]:
# using position .iloc
print("Element at position '2':")
print("Value: ", s.iloc[2])
print("Index: ",s.index[2])

Element at position '2':
Value:  120
Index:  orange

### 1.5. Series Properties & Methods

In [14]:
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'], name='Prices')

print("Basic Properties:")
print(f"Index: {s.index.tolist()}")
print(f"Values: {s.values.tolist()}")
print(f"Data type: {s.dtype}")
print(f"Name: {s.name}")
print(f"Length: {s.size}")

print("\nStatistical Methods:")
print(f"Sum: {s.sum()}")
print(f"Mean: {s.mean():.2f}")
print(f"Median: {s.median():.2f}")
print(f"Min: {s.min()}")
print(f"Max: {s.max()}")
print(f"Std Dev: {s.std():.2f}")

print("\nDescribe (Summary Statistics):")
display(s.describe())

Basic Properties:
Index: ['a', 'b', 'c', 'd', 'e']
Values: [10, 20, 30, 40, 50]
Data type: int64
Name: Prices
Length: 5

Statistical Methods:
Sum: 150
Mean: 30.00
Median: 30.00
Min: 10
Max: 50
Std Dev: 15.81

Describe (Summary Statistics):

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
Name: Prices, dtype: float64

### 1.6. Series Operations

In [15]:
prices = {'apple': 100, 'banana': 150, 'orange': 120, 'mango': 200}
prices_ser = pd.Series(prices)

discounts = {'apple': 10,  'orange': 10, 'mango': 5, 'grapes': 8}
discounts_ser = pd.Series(discounts)

prices_ser - discounts_ser

apple      90.0
banana      NaN
grapes      NaN
mango     195.0
orange    110.0
dtype: float64

---
### Note: Series do not just support elementwise operation. Support index based operation.
---

In [16]:
prices_ser.subtract(discounts_ser, fill_value = 0)

apple      90.0
banana    150.0
grapes     -8.0
mango     195.0
orange    110.0
dtype: float64

### 1.7. String Methods

In [17]:
s = pd.Series(['apple', 'banana', 'ORANGE', 'grape'])
print(f'To title case:\n{s.str.upper()}')

To title case:
0     APPLE
1    BANANA
2    ORANGE
3     GRAPE
dtype: str

In [18]:
string = 'Shyam'
print(dir(string))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

In [19]:
print(f'To title case:\n{s.str.title()}')

To title case:
0     Apple
1    Banana
2    Orange
3     Grape
dtype: str

### 1.8. DateTime Functions

In [20]:
s = pd.Series(["7 July 2021", "14 December 2015", "12 March 1986", "8 August 1983"]) # in string

dates = pd.to_datetime(s)
dates

0   2021-07-07
1   2015-12-14
2   1986-03-12
3   1983-08-08
dtype: datetime64[us]

In [21]:
# the month for each date
dates.iloc[2].month

3

In [22]:
year = dates.dt.year
year

0    2021
1    2015
2    1986
3    1983
dtype: int32

In [23]:
month = dates.dt.month
month

0     7
1    12
2     3
3     8
dtype: int32

In [24]:
month_name = dates.dt.strftime("%B")
month_name

0        July
1    December
2       March
3      August
dtype: str

### 1.9. Custom Functions

In [25]:
employees = pd.Series([5, 8, 9, 8.5, 7, 9.5], index = ['John', 'Kate', 'Prince', 'Amit', 'Nayan', 'Leah'], name = 'Performance Score')
employees

John      5.0
Kate      8.0
Prince    9.0
Amit      8.5
Nayan     7.0
Leah      9.5
Name: Performance Score, dtype: float64

In [27]:
res = []
for score in employees:
    if score >= 9 : r = 'promote & raise'
    elif score >= 7.5: r = 'raise'
    elif score >= 6 : r = 'review'
    else : r = 'monitor'
    res.append(r)
result = pd.Series(res, index = employees.index, dtype = str)
result

John              monitor
Kate                raise
Prince    promote & raise
Amit                raise
Nayan              review
Leah      promote & raise
dtype: str

In [ ]:
# Wrapping it in a function
def res(score):
    if score >= 9 : return 'promote & raise'
    elif score >= 7.5: return 'raise'
    elif score >= 6 : return'review'
    else : return 'monitor'
result = employees.apply(res)
result

In [29]:
result.str.title()

JOHN              Monitor
KATE                Raise
PRINCE    Promote & Raise
AMIT                Raise
NAYAN              Review
LEAH      Promote & Raise
dtype: str

In [30]:
result.index = result.index.str.upper()
result

JOHN              monitor
KATE                raise
PRINCE    promote & raise
AMIT                raise
NAYAN              review
LEAH      promote & raise
dtype: str

## 2. DataFrames

In [33]:
# Create a simple dataframe
data = {
    'Name' : ['Alice', 'Bob', 'Carol'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000
2  Carol   35   70000

In [32]:
# CREATE THE DATAFRAME
brics = pd.DataFrame({
    'Country': ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
    'Capital': ['Brasília', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
    'Population_Millions': [215.3, 144.4, 1417.2, 1425.9, 60.1],
    'GDP_Trillions_USD': [2.09, 2.06, 3.73, 17.96, 0.41],
    'GDP_Per_Capita_USD': [9725, 14280, 2639, 12720, 6800],
    'Area_Million_Sq_km': [8.51, 17.10, 3.29, 9.60, 1.22]
})
brics

,Country,Capital,Population_Millions,GDP_Trillions_USD,GDP_Per_Capita_USD,Area_Million_Sq_km
0,Brazil,Brasília,215.3,2.09,9725,8.51
1,Russia,Moscow,144.4,2.06,14280,17.10
2,India,New Delhi,1417.2,3.73,2639,3.29
3,China,Beijing,1425.9,17.96,12720,9.60
4,South Africa,Pretoria,60.1,0.41,6800,1.22

### 2.1 Data Inport

In [35]:
filepath = 'datasets/titanic/train.csv'
df = pd.read_csv(filepath)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 2.2 Snapshot of Data

In [36]:
df.head() # top 5 rows by default

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [38]:
df.tail() # bottom 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [39]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### 2.3 Structure / Info

In [40]:
print(f"Type of data : {type(df)}")
print(f"No. of Rows & columns : {df.shape}")
print(f'Row labels : {df.index}')
print(f'Column labels :\n{df.columns}')
print('Column datatypes:')
print(df.dtypes)

Type of data : <class 'pandas.DataFrame'>
No. of Rows & columns : (891, 12)
Row labels : RangeIndex(start=0, stop=891, step=1)
Column labels :
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')
Column datatypes:
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [41]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
None

### 2.4 Accessing Rows and Columns

In [42]:
df.Name # returns a series

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [43]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [44]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [45]:
df.loc[100]

PassengerId                        101
Survived                             0
Pclass                               3
Name           Petranec, Miss. Matilda
Sex                             female
Age                               28.0
SibSp                                0
Parch                                0
Ticket                          349245
Fare                            7.8958
Cabin                              NaN
Embarked                             S
Name: 100, dtype: object

In [46]:
df.iloc[102]

PassengerId                          103
Survived                               0
Pclass                                 1
Name           White, Mr. Richard Frasar
Sex                                 male
Age                                 21.0
SibSp                                  0
Parch                                  1
Ticket                             35281
Fare                             77.2875
Cabin                                D26
Embarked                               S
Name: 102, dtype: object

In [47]:
df.loc[100:105] # both start and stop are included

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
102,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
103,104,0,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,NaN,S
104,105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.9250,NaN,S
105,106,0,3,"Mionoff, Mr. Stoytcho",male,28.0,0,0,349207,7.8958,NaN,S

In [ ]:
df.iloc[100:105] # end index (stop index) is excluded

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
102,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
103,104,0,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,NaN,S
104,105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.9250,NaN,S

In [ ]:
df.loc[100:104, ['Name', 'Age','Pclass']] # selects required columns in range

                                 Name   Age  Pclass
100           Petranec, Miss. Matilda  28.0       3
101  Petroff, Mr. Pastcho ("Pentcho")   NaN       3
102         White, Mr. Richard Frasar  21.0       1
103        Johansson, Mr. Gustaf Joel  33.0       3
104    Gustafsson, Mr. Anders Vilhelm  37.0       3

In [ ]:
df.loc[100:104, 'Pclass':'Age'] # select range of columns

     Pclass                              Name     Sex   Age
100       3           Petranec, Miss. Matilda  female  28.0
101       3  Petroff, Mr. Pastcho ("Pentcho")    male   NaN
102       1         White, Mr. Richard Frasar    male  21.0
103       3        Johansson, Mr. Gustaf Joel    male  33.0
104       3    Gustafsson, Mr. Anders Vilhelm    male  37.0

In [51]:
df.iloc[100:104, 2:6] # select range of column using column index

     Pclass                              Name     Sex   Age
100       3           Petranec, Miss. Matilda  female  28.0
101       3  Petroff, Mr. Pastcho ("Pentcho")    male   NaN
102       1         White, Mr. Richard Frasar    male  21.0
103       3        Johansson, Mr. Gustaf Joel    male  33.0

### 2.5 Managing Index and Column labels

In [ ]:
df.head(2) ## observe that index is numbers starting from 0 by default

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [ ]:
df.set_index('PassengerId') # Assigns passengerId as index and returns a new Dataframe

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

#### <b>```inplace``` option
- makes the changes in the same dataframe (same memory address)

In [54]:
df_new = df.set_index('PassengerId')
df_new.head(2)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

---
##### <font size = 4 color = steelblue> <b>Note: Inplace modification is not recommended if the exploration is still in experimental stage

---

In [ ]:
df.set_index('PassengerId', inplace = True)

In [57]:
df.head(2)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [58]:
df.index

RangeIndex(start=1, stop=892, step=1, name='PassengerId')

- Revert index operation

In [59]:
df.reset_index()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [60]:
df.reset_index(inplace = True)

In [61]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

### 2.6 Renaming
```python
df.rename(index = {'old row name': 'new row name'}, columns = {'old col name': 'new col name'})

In [62]:
brics # using brics dataframe

,Country,Capital,Population_Millions,GDP_Trillions_USD,GDP_Per_Capita_USD,Area_Million_Sq_km
0,Brazil,Brasília,215.3,2.09,9725,8.51
1,Russia,Moscow,144.4,2.06,14280,17.10
2,India,New Delhi,1417.2,3.73,2639,3.29
3,China,Beijing,1425.9,17.96,12720,9.60
4,South Africa,Pretoria,60.1,0.41,6800,1.22

In [63]:
brics.rename(columns = {'Population_Millions' : 'Pop_M', 'GDP_Trillions_USD' : "GDP_TUSD", 'GDP_Per_Capita_USD': 'GDP_percap'})

        Country    Capital   Pop_M  GDP_TUSD  GDP_percap  Area_Million_Sq_km
0        Brazil   Brasília   215.3      2.09        9725                8.51
1        Russia     Moscow   144.4      2.06       14280               17.10
2         India  New Delhi  1417.2      3.73        2639                3.29
3         China    Beijing  1425.9     17.96       12720                9.60
4  South Africa   Pretoria    60.1      0.41        6800                1.22

In [64]:
brics

,Country,Capital,Population_Millions,GDP_Trillions_USD,GDP_Per_Capita_USD,Area_Million_Sq_km
0,Brazil,Brasília,215.3,2.09,9725,8.51
1,Russia,Moscow,144.4,2.06,14280,17.10
2,India,New Delhi,1417.2,3.73,2639,3.29
3,China,Beijing,1425.9,17.96,12720,9.60
4,South Africa,Pretoria,60.1,0.41,6800,1.22

In [65]:
brics.rename(columns = {'Population_Millions' : 'Pop_M', 'GDP_Trillions_USD' : "GDP_TUSD", 'GDP_Per_Capita_USD': 'GDP_percap', 'Area_Million_Sq_km':'Aea_MSqKm'},
             index = {k: val for k, val in zip(range(0,5), brics.Country.str[0])},
            # inplace = True
            )

        Country    Capital   Pop_M  GDP_TUSD  GDP_percap  Aea_MSqKm
B        Brazil   Brasília   215.3      2.09        9725       8.51
R        Russia     Moscow   144.4      2.06       14280      17.10
I         India  New Delhi  1417.2      3.73        2639       3.29
C         China    Beijing  1425.9     17.96       12720       9.60
S  South Africa   Pretoria    60.1      0.41        6800       1.22

In [66]:
brics.Country.str[0]

0    B
1    R
2    I
3    C
4    S
Name: Country, dtype: str

In [67]:
brics.index = brics.Country.str[0]

### 2.7 Adding Rows and/or Columns

#### Columns -->
1. single value (constant)
2. using a another series/list
3. insert at a position

In [68]:
pd.cut(df['Age'], bins=[0, 12, 18, 65, 100],labels=['Child', 'Teen', 'Adult', 'Senior'])

0      Adult
1      Adult
2      Adult
3      Adult
4      Adult
       ...
886    Adult
887    Adult
888      NaN
889    Adult
890    Adult
Name: Age, Length: 891, dtype: category
Categories (4, str): ['Child' < 'Teen' < 'Adult' < 'Senior']

In [69]:
# Add single column with categorization
df_copy = df.copy()
df_copy['Age_Category'] = pd.cut(df_copy['Age'], 
                                  bins=[0, 12, 18, 65, 100],
                                  labels=['Child', 'Teen', 'Adult', 'Senior'])
print('Added Age_Category column:')
df_copy.head(10)

Added Age_Category column:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Adult
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Child
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Teen

In [71]:
# multiple columns
df_copy_2 = df.assign(Age_category = pd.cut(df_copy['Age'], 
                                  bins=[0, 12, 18, 65, 100],
                                  labels=['Child', 'Teen', 'Adult', 'Senior']),
                     flag = 'train')
df_copy_2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_category,flag
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,train
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,train
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,train
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,train
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,train
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,train
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN,train
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,train
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,train

### 2.9 Append -> Concat
```python
pd.concat([list of series/dfs], axis = 0/1)
```

In [72]:
df_test = pd.read_csv('datasets/titanic/test.csv')
df_test.head(2)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S

In [73]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 2.10 Drop Rows and/or Columns

In [74]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [75]:
df.drop(columns = ['Cabin']).head(2) # new dataframe inplace option

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C

In [76]:
df.drop(columns = ['Cabin', 'Ticket']).head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C

In [ ]:
df.set_index('PassengerId', inplace = True)

In [79]:
df.head(7)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [80]:
df.drop(columns = ['Cabin', 'Ticket'], index = [5,7]).head(7)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
PassengerId,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,8.4583,Q
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,21.0750,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,11.1333,S

---
- Drops by labels only 
- `inplace` option available but not recommended.

---

### 2.11 Conditional Filtering

In [81]:
# get the data for all females
df.Sex == 'female'

PassengerId
1      False
2       True
3       True
4       True
5      False
       ...
887    False
888     True
889     True
890    False
891    False
Name: Sex, Length: 891, dtype: bool

In [82]:
df[df.Sex == 'female']

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [83]:
df[(df.Sex == 'female') & (df.Age <5)] # Get all female passengers with age > 5

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S
298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
375,0,3,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,21.0750,NaN,S
382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S
645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C
751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S

In [84]:
# travellers of pclass 01 or 2
df[(df.Pclass == 1) | (df.Pclass == 2)]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [85]:
df[df.Pclass.isin([1,2])]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### 2.12 Sorting the Data

In [86]:
df.sort_values('Pclass') # in ascending order

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
446,1,1,"Dodge, Master. Washington",male,4.0,0,2,33638,81.8583,A34,S
311,1,1,"Hays, Miss. Margaret Bechstein",female,24.0,0,0,11767,83.1583,C54,C
310,1,1,"Francatelli, Miss. Laura Mabel",female,30.0,0,0,PC 17485,56.9292,E36,C
308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.0,1,0,PC 17758,108.9000,C65,C
307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
380,0,3,"Gustafsson, Mr. Karl Gideon",male,19.0,0,0,347069,7.7750,NaN,S
382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.0,0,2,2653,15.7417,NaN,C
383,0,3,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S
372,0,3,"Wiklund, Mr. Jakob Alfred",male,18.0,1,0,3101267,6.4958,NaN,S
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [87]:
df.sort_values('Pclass', ascending = False) # in ascending order

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
512,0,3,"Webber, Mr. James",male,NaN,0,0,SOTON/OQ 3101316,8.0500,NaN,S
501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S
502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
503,0,3,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,330909,7.6292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.0,0,0,PC 17482,49.5042,C90,C
712,0,1,"Klaber, Mr. Herman",male,NaN,0,0,113028,26.5500,C124,S
713,1,1,"Taylor, Mr. Elmer Zebley",male,48.0,1,0,19996,52.0000,C126,S
446,1,1,"Dodge, Master. Washington",male,4.0,0,2,33638,81.8583,A34,S

In [88]:
df.sort_values(['Sex', 'Age'])

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S
860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S

In [89]:
df.sort_values(['Sex', 'Age'], ascending = [True, False], na_position= 'first')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C

### 2.12 Statistical Analysis

In [90]:
df.describe() # default picks up numerical data

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [91]:
# Mean, Median, Mode
print(f'Mean Age: {df["Age"].mean():.2f}')
print(f'Median Age: {df["Age"].median():.2f}')
print(f'Mode Age: {df["Age"].mode().values[0]:.2f}')
print(f'\nStd Dev Fare: {df["Fare"].std():.2f}')
print(f'Variance Fare: {df["Fare"].var():.2f}')

Mean Age: 29.70
Median Age: 28.00
Mode Age: 24.00

Std Dev Fare: 49.69
Variance Fare: 2469.44

In [92]:
# Correlation matrix
print('Correlation matrix:')
df[['Survived', 'Age', 'Fare', 'Pclass']].corr()

Correlation matrix:

          Survived       Age      Fare    Pclass
Survived  1.000000 -0.077221  0.257307 -0.338481
Age      -0.077221  1.000000  0.096067 -0.369226
Fare      0.257307  0.096067  1.000000 -0.549500
Pclass   -0.338481 -0.369226 -0.549500  1.000000

### 2.13 Aggregation

In [93]:
# Group by single column
print('Survival rate by class:')

df.groupby('Pclass').count()[['Survived']]

Survival rate by class:

        Survived
Pclass
1            216
2            184
3            491

In [94]:
df.groupby('Pclass')[['Survived']].count()

        Survived
Pclass
1            216
2            184
3            491

In [95]:
df.groupby('Pclass')[['Survived']].agg(['count', 'sum', 'mean'])

       Survived
          count  sum      mean
Pclass
1           216  136  0.629630
2           184   87  0.472826
3           491  119  0.242363

In [96]:
# for custom functions --> range
def percentage(x):
    return f'{round(x.mean() * 100,1)} %'

In [97]:
df.groupby('Pclass')[['Survived']].agg(['count', 'sum', 'mean', percentage])

       Survived
          count  sum      mean percentage
Pclass
1           216  136  0.629630     63.0 %
2           184   87  0.472826     47.3 %
3           491  119  0.242363     24.2 %

In [98]:
df.groupby(['Pclass', 'Sex'])[['Survived']].agg(['count', 'sum', 'mean', percentage]).unstack()

       Survived
          count         sum           mean           percentage
Sex      female male female male    female      male     female    male
Pclass
1            94  122     91   45  0.968085  0.368852     96.8 %  36.9 %
2            76  108     70   17  0.921053  0.157407     92.1 %  15.7 %
3           144  347     72   47  0.500000  0.135447     50.0 %  13.5 %

In [99]:
# pivot table
df.pivot_table(index = 'Pclass',
              columns = 'Sex',
              values = 'Survived',
              aggfunc = ['count', 'sum', 'mean', percentage] )

        count         sum           mean           percentage
Sex    female male female male    female      male     female    male
Pclass
1          94  122     91   45  0.968085  0.368852     96.8 %  36.9 %
2          76  108     70   17  0.921053  0.157407     92.1 %  15.7 %
3         144  347     72   47  0.500000  0.135447     50.0 %  13.5 %

## Additional Resources

- [Pandas Documentation](https://pandas.pydata.org/docs/getting_started/index.html#getting-started)
- [Pandas User guide](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)